import { deleteMatch, saveMatch } from '@/app/admin/content-actions'
import { requireAdmin } from '@/lib/auth/require-admin'

const field = 'mt-1 w-full rounded border border-slate-300 px-2 py-1.5 text-sm'

export default async function MatchesAdminPage() {
  const { supabase } = await requireAdmin()
  const [{ data: teams }, { data: matches }] = await Promise.all([supabase.from('teams').select('id,name').order('name'), supabase.from('matches').select('*, teams(name)').order('match_date', { ascending: false })])
  return <section className="space-y-8"><div><p className="text-sm font-semibold text-red-600">Fikstür ve sonuçlar</p><h1 className="text-3xl font-bold">Maç yönetimi</h1></div><MatchForm action={saveMatch} teams={teams ?? []} />
    <div className="space-y-3"><h2 className="text-xl font-bold">Kayıtlar</h2>{matches?.length ? matches.map((match) => <details key={match.id} className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">{match.home_team} – {match.away_team} <span className="text-sm font-normal text-slate-500">{match.match_date ?? 'Tarih yok'}</span></summary><div className="mt-4"><MatchForm action={saveMatch} teams={teams ?? []} match={match} /><form action={deleteMatch} className="mt-3 flex gap-2"><input type="hidden" name="id" value={match.id} /><input name="confirmation" required placeholder="DELETE yazın" className={field} /><button className="rounded border border-red-700 px-3 text-red-700">Sil</button></form></div></details>) : <p className="rounded border border-dashed p-6 text-slate-500">Henüz maç yok.</p>}</div></section>
}

function MatchForm({ action, teams, match }: { action: (data: FormData) => Promise<void>; teams: { id: string; name: string }[]; match?: Record<string, unknown> }) {
  const value = (key: string) => String(match?.[key] ?? '')
  return <form action={action} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><input type="hidden" name="id" value={value('id')} /><label>Takım<select required name="teamId" defaultValue={value('team_id')} className={field}><option value="">Seçin</option>{teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>Ev sahibi<input required name="homeTeam" defaultValue={value('home_team')} className={field} /></label><label>Deplasman<input required name="awayTeam" defaultValue={value('away_team')} className={field} /></label><label>Organizasyon<input required name="competition" defaultValue={value('competition')} className={field} /></label><label>Tarih<input type="date" name="matchDate" defaultValue={value('match_date')} className={field} /></label><label>Saat<input type="time" name="kickoffTime" defaultValue={value('kickoff_time')} className={field} /></label><label>Stadyum<input name="stadium" defaultValue={value('stadium')} className={field} /></label><label>Hafta<input type="number" name="week" defaultValue={value('week')} className={field} /></label><label>Ev skoru<input type="number" name="homeScore" defaultValue={value('home_score')} className={field} /></label><label>Dep. skoru<input type="number" name="awayScore" defaultValue={value('away_score')} className={field} /></label><label>Durum<select name="status" defaultValue={value('status') || 'scheduled'} className={field}>{['scheduled','postponed','completed','cancelled'].map((x) => <option key={x}>{x}</option>)}</select></label><label>İç saha<input type="checkbox" name="isHome" defaultChecked={Boolean(match?.is_home ?? true)} /></label><label>Aktif<input type="checkbox" name="isActive" defaultChecked={Boolean(match?.is_active ?? true)} /></label><button className="rounded bg-red-700 px-4 py-2 font-semibold text-white">{match ? 'Güncelle' : 'Maç ekle'}</button></form>
}
