import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicTeams } from '@/lib/content/public'
import { Users } from 'lucide-react'

type Player = { id: string; is_active: boolean; shirt_number: number | null; full_name: string; position: string }
type StaffMember = { id: string; is_active: boolean; full_name: string; job_title: string }

export default async function TeamsPage() {
  const teams = await getPublicTeams()
  return <div className="min-h-screen overflow-x-clip bg-slate-50 text-slate-900"><Header /><section className="border-b border-red-900 bg-gradient-to-br from-red-800 via-red-700 to-slate-900 py-14 text-white sm:py-16"><div className="container mx-auto px-4"><p className="text-sm font-bold uppercase tracking-[.2em] text-red-200">Kulüp yapısı</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Takımlar ve kadro</h1><p className="mt-4 max-w-2xl text-base leading-7 text-red-100 sm:text-lg">Kulübümüzün aktif takımları, oyuncuları ve teknik ekipleri.</p></div></section><main className="container mx-auto space-y-6 px-4 py-10 sm:py-14">{teams.length ? teams.map((team) => <section key={team.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 bg-slate-50 px-5 py-5 sm:px-7"><p className="text-xs font-bold uppercase tracking-wide text-red-700">{team.league || team.age_group || 'Kulüp takımı'}</p><h2 className="mt-1 text-2xl font-black tracking-tight text-slate-900">{team.name}</h2>{team.description ? <p className="mt-3 max-w-3xl leading-7 text-slate-600">{team.description}</p> : null}</div><div className="grid gap-7 p-5 lg:grid-cols-2 lg:p-7"><div><h3 className="text-lg font-bold text-slate-900">Oyuncular</h3>{team.players?.length ? <ul className="mt-4 grid gap-2 sm:grid-cols-2">{(team.players as Player[]).filter((player) => player.is_active).map((player) => <li key={player.id} className="min-w-0 rounded-xl border border-slate-200 px-3 py-3"><span className="block truncate font-semibold text-slate-900">{player.shirt_number ?? '–'} · {player.full_name}</span><p className="mt-1 truncate text-sm text-slate-500">{player.position}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">Bu takım için henüz oyuncu eklenmedi.</p>}</div><div><h3 className="text-lg font-bold text-slate-900">Teknik ekip</h3>{team.staff?.length ? <ul className="mt-4 grid gap-2 sm:grid-cols-2">{(team.staff as StaffMember[]).filter((person) => person.is_active).map((person) => <li key={person.id} className="min-w-0 rounded-xl border border-slate-200 px-3 py-3"><span className="block truncate font-semibold text-slate-900">{person.full_name}</span><p className="mt-1 truncate text-sm text-slate-500">{person.job_title}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">Bu takım için henüz teknik ekip eklenmedi.</p>}</div></div></section>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Users className="mx-auto h-12 w-12 text-slate-300" /><h2 className="mt-4 text-xl font-bold text-slate-700">Henüz aktif takım yok</h2><p className="mt-2 text-slate-500">Takımlar yayınlandığında burada listelenecek.</p></div>}</main><Footer /></div>
}
