import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicTeams } from '@/lib/content/public'
import { Users } from 'lucide-react'

type Player = { id: string; is_active: boolean; shirt_number: number | null; full_name: string; position: string }
type StaffMember = { id: string; is_active: boolean; full_name: string; job_title: string }

export default async function TeamsPage() {
  const teams = await getPublicTeams()
  return <div className="min-h-screen bg-gray-50"><Header /><section className="bg-gradient-to-r from-red-600 via-red-700 to-red-800 py-16 text-white"><div className="container mx-auto px-4 text-center"><h1 className="text-4xl font-bold md:text-5xl">Takımlar ve kadro</h1><p className="mt-4 text-xl text-red-100">Kulübümüzün aktif takımları ve teknik ekipleri</p></div></section><main className="container mx-auto space-y-8 px-4 py-12">{teams.length ? teams.map((team) => <section key={team.id} className="rounded-xl bg-white p-6 shadow"><div className="border-b pb-4"><h2 className="text-2xl font-bold text-gray-900">{team.name}</h2><p className="mt-1 text-red-700">{team.league || team.age_group || 'Lig bilgisi belirtilmedi'}</p>{team.description ? <p className="mt-3 text-gray-600">{team.description}</p> : null}</div><div className="mt-6 grid gap-8 lg:grid-cols-2"><div><h3 className="text-lg font-bold">Oyuncular</h3>{team.players?.length ? <ul className="mt-3 grid gap-2 sm:grid-cols-2">{(team.players as Player[]).filter((player) => player.is_active).map((player) => <li key={player.id} className="rounded border p-3"><span className="font-semibold">{player.shirt_number ?? '–'} · {player.full_name}</span><p className="text-sm text-gray-500">{player.position}</p></li>)}</ul> : <p className="mt-3 text-sm text-gray-500">Bu takım için henüz oyuncu eklenmedi.</p>}</div><div><h3 className="text-lg font-bold">Teknik ekip</h3>{team.staff?.length ? <ul className="mt-3 space-y-2">{(team.staff as StaffMember[]).filter((person) => person.is_active).map((person) => <li key={person.id} className="rounded border p-3"><span className="font-semibold">{person.full_name}</span><p className="text-sm text-gray-500">{person.job_title}</p></li>)}</ul> : <p className="mt-3 text-sm text-gray-500">Bu takım için henüz teknik ekip eklenmedi.</p>}</div></div></section>) : <div className="rounded-lg bg-white p-12 text-center shadow"><Users className="mx-auto h-16 w-16 text-gray-300" /><h2 className="mt-4 text-xl font-semibold text-gray-700">Henüz aktif takım yok</h2><p className="mt-2 text-gray-500">Takımlar yayınlandığında burada listelenecek.</p></div>}</main><Footer /></div>
}
