import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicNews } from '@/lib/content/public'
import { Calendar, Newspaper } from 'lucide-react'

const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value)) : 'Tarih belirtilmedi'

export default async function NewsPage() {
  const news = await getPublicNews()
  return <div className="min-h-screen overflow-x-clip bg-slate-50 text-slate-900"><Header /><section className="border-b border-red-900 bg-gradient-to-br from-red-800 via-red-700 to-slate-900 py-14 text-white sm:py-16"><div className="container mx-auto px-4"><p className="text-sm font-bold uppercase tracking-[.2em] text-red-200">Kulüpten</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Haberler</h1><p className="mt-4 max-w-2xl text-base leading-7 text-red-100 sm:text-lg">Kulübümüzden son haberler ve gelişmeler.</p></div></section><main className="container mx-auto px-4 py-10 sm:py-14"><div className="mb-7"><p className="text-sm font-bold uppercase tracking-wide text-red-700">Güncel</p><h2 className="mt-1 text-2xl font-black tracking-tight">Duyurular</h2></div>{news.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{news.map((item) => <article key={item.id} className="flex min-w-0 flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-red-200 hover:shadow-lg sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3 text-sm"><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-800">{item.category}</span><span className="flex items-center text-xs text-slate-500"><Calendar className="mr-1 h-4 w-4" />{formatDate(item.published_at)}</span></div><h3 className="mt-5 text-xl font-black tracking-tight text-slate-900">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{item.summary}</p><details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-sm font-bold text-red-700">Haberi oku</summary><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-700">{item.content}</p></details></article>)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Newspaper className="mx-auto h-12 w-12 text-slate-300" /><h3 className="mt-4 text-xl font-bold text-slate-700">Henüz yayınlanmış haber yok</h3><p className="mt-2 text-slate-500">Yeni duyurular burada görünecek.</p></div>}</main><Footer /></div>
}
