import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicMatches, getPublicNews, getPublicSettings, getPublicTeams } from '@/lib/content/public'
import Link from 'next/link'
import { Calendar, Newspaper, Users } from 'lucide-react'

type ActivePlayer = { is_active: boolean }

export default async function HomePage() {
  const [settings, teams, matches, news] = await Promise.all([getPublicSettings(), getPublicTeams(), getPublicMatches(), getPublicNews(3)])
  const upcoming = matches.filter((match) => match.status === 'scheduled').slice(0, 3)
  const playerCount = teams.reduce((total, team) => total + ((team.players as ActivePlayer[] | undefined)?.filter((player) => player.is_active).length ?? 0), 0)
  return <div className="min-h-screen bg-gray-50"><Header /><main><section className="bg-gradient-to-r from-red-600 via-red-700 to-red-800 py-20 text-white"><div className="container mx-auto px-4 text-center"><h1 className="text-4xl font-bold md:text-6xl">{settings?.home_hero_title || 'Üsküdar İcadiye Spor'}</h1><p className="mx-auto mt-5 max-w-3xl text-xl text-red-100">{settings?.home_hero_text || 'Gelenekten geleceğe, spor ruhuyla.'}</p><div className="mx-auto mt-10 grid max-w-2xl grid-cols-2 gap-4 md:grid-cols-3"><div className="rounded-lg bg-white/15 p-4"><div className="text-2xl font-bold">{teams.length}</div><div className="text-sm">Aktif takım</div></div><div className="rounded-lg bg-white/15 p-4"><div className="text-2xl font-bold">{playerCount}</div><div className="text-sm">Aktif sporcu</div></div><div className="col-span-2 rounded-lg bg-white/15 p-4 md:col-span-1"><div className="text-2xl font-bold">1951</div><div className="text-sm">Kuruluş</div></div></div></div></section><section className="container mx-auto grid gap-8 px-4 py-14 lg:grid-cols-2"><div><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">Son haberler</h2><Link className="text-sm font-semibold text-red-700" href="/haberler">Tümü</Link></div>{news.length ? <div className="mt-5 space-y-4">{news.map((item) => <article key={item.id} className="rounded-lg bg-white p-5 shadow"><p className="text-sm font-semibold text-red-700">{item.category}</p><h3 className="mt-1 text-lg font-bold">{item.title}</h3><p className="mt-2 text-gray-600">{item.summary}</p></article>)}</div> : <Empty icon={<Newspaper />} text="Henüz yayınlanmış haber yok." />}</div><div><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">Yaklaşan maçlar</h2><Link className="text-sm font-semibold text-red-700" href="/maclar">Tümü</Link></div>{upcoming.length ? <div className="mt-5 space-y-4">{upcoming.map((match) => <article key={match.id} className="rounded-lg bg-white p-5 shadow"><p className="text-sm text-gray-500">{match.competition}</p><h3 className="mt-1 font-bold">{match.home_team} <span className="text-gray-500">–</span> {match.away_team}</h3><p className="mt-2 text-sm text-gray-600">{match.match_date || 'Tarih belirtilmedi'}{match.kickoff_time ? ` · ${match.kickoff_time.slice(0, 5)}` : ''}</p></article>)}</div> : <Empty icon={<Calendar />} text="Yaklaşan maç bulunmuyor." />}</div></section><section className="bg-white py-14"><div className="container mx-auto px-4 text-center"><Users className="mx-auto h-10 w-10 text-red-700" /><h2 className="mt-3 text-2xl font-bold">Kulübümüz</h2><p className="mx-auto mt-3 max-w-3xl text-gray-600">{settings?.club_description || 'Kulübümüzün güncel bilgileri yakında paylaşılacak.'}</p><Link className="mt-6 inline-block rounded bg-red-700 px-5 py-3 font-semibold text-white hover:bg-red-800" href="/takimlar">Takımlarımızı inceleyin</Link></div></section></main><Footer /></div>
}

function Empty({ icon, text }: { icon: React.ReactNode; text: string }) {
  return <div className="mt-5 rounded-lg bg-white p-8 text-center text-gray-500 shadow"><span className="mx-auto block h-8 w-8 text-gray-300">{icon}</span><p className="mt-3">{text}</p></div>
}
