import Link from 'next/link'
import { Facebook, Instagram, Mail, MapPin, Phone, Youtube } from 'lucide-react'
import { getPublicSettings } from '@/lib/content/public'

export default async function Footer() {
  const settings = await getPublicSettings()
  const social = [{ href: settings?.instagram_url, label: 'Instagram', Icon: Instagram }, { href: settings?.facebook_url, label: 'Facebook', Icon: Facebook }, { href: settings?.youtube_url, label: 'YouTube', Icon: Youtube }].filter((item): item is { href: string; label: string; Icon: typeof Instagram } => Boolean(item.href))
  return <footer className="border-t border-slate-800 bg-slate-950 text-white"><div className="container mx-auto grid gap-8 px-4 py-12 sm:grid-cols-2 lg:grid-cols-3"><div><h2 className="text-lg font-bold">Üsküdar İcadiye Spor</h2><p className="mt-3 max-w-sm text-sm leading-6 text-slate-400">{settings?.club_description || 'Kulübümüzden haberler, maçlar ve kadro bilgileri.'}</p></div><div><h2 className="text-lg font-bold">Hızlı bağlantılar</h2><div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2 text-sm text-slate-400"><Link className="hover:text-white" href="/takimlar">Takımlar</Link><Link className="hover:text-white" href="/maclar">Maçlar</Link><Link className="hover:text-white" href="/haberler">Haberler</Link><Link className="hover:text-white" href="/galeri">Galeri</Link></div></div><div><h2 className="text-lg font-bold">İletişim</h2><div className="mt-3 space-y-2 text-sm text-slate-400">{settings?.address ? <p className="flex gap-2"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-red-400" />{settings.address}</p> : null}{settings?.phone ? <a className="flex gap-2 hover:text-white" href={`tel:${settings.phone}`}><Phone className="h-4 w-4 shrink-0 text-red-400" />{settings.phone}</a> : null}{settings?.email ? <a className="flex min-w-0 gap-2 hover:text-white" href={`mailto:${settings.email}`}><Mail className="mt-0.5 h-4 w-4 shrink-0 text-red-400" /><span className="break-all">{settings.email}</span></a> : null}</div>{social.length ? <div className="mt-4 flex gap-3">{social.map(({ href, label, Icon }) => <a key={label} href={href} aria-label={label} className="rounded-full bg-slate-800 p-2 transition hover:bg-red-700"><Icon className="h-5 w-5" /></a>)}</div> : null}</div></div><div className="container mx-auto border-t border-slate-800 px-4 py-5 text-center text-xs text-slate-500">© {new Date().getFullYear()} Üsküdar İcadiye Spor Kulübü.</div></footer>
}
