import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicMatches } from '@/lib/content/public'
import { Calendar, MapPin } from 'lucide-react'

const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value)) : 'Tarih belirtilmedi'
const labels = { scheduled: 'Planlandı', postponed: 'Ertelendi', completed: 'Tamamlandı', cancelled: 'İptal edildi' }

export default async function MatchesPage() {
  const matches = await getPublicMatches()
  return <div className="min-h-screen bg-gray-50"><Header /><section className="bg-gradient-to-r from-red-600 via-red-700 to-red-800 py-16 text-white"><div className="container mx-auto px-4 text-center"><h1 className="text-4xl font-bold md:text-5xl">Maçlar</h1><p className="mt-4 text-xl text-red-100">Fikstür ve sonuçlar</p></div></section><main className="container mx-auto px-4 py-12">{matches.length ? <div className="grid gap-5 lg:grid-cols-2">{matches.map((match) => <article key={match.id} className="rounded-xl bg-white p-6 shadow"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-red-700">{match.teams?.name || 'Takım'}</p><p className="mt-1 text-sm text-gray-500">{match.competition}{match.week ? ` · ${match.week}. hafta` : ''}</p></div><span className="rounded-full bg-gray-100 px-3 py-1 text-sm text-gray-700">{labels[String(match.status) as keyof typeof labels] ?? 'Durum bilinmiyor'}</span></div><div className="my-6 grid grid-cols-3 items-center text-center"><strong>{match.home_team}</strong><span className="font-bold text-gray-500">{match.status === 'completed' ? `${match.home_score} - ${match.away_score}` : 'VS'}</span><strong>{match.away_team}</strong></div><div className="grid gap-2 text-sm text-gray-600 sm:grid-cols-2"><span className="flex items-center"><Calendar className="mr-2 h-4 w-4 text-red-600" />{formatDate(match.match_date)}{match.kickoff_time ? ` · ${match.kickoff_time.slice(0, 5)}` : ''}</span>{match.stadium ? <span className="flex items-center"><MapPin className="mr-2 h-4 w-4 text-red-600" />{match.stadium}</span> : null}</div></article>)}</div> : <div className="rounded-lg bg-white p-12 text-center shadow"><Calendar className="mx-auto h-16 w-16 text-gray-300" /><h2 className="mt-4 text-xl font-semibold text-gray-700">Henüz maç kaydı yok</h2><p className="mt-2 text-gray-500">Yeni fikstür ve sonuçlar burada görünecek.</p></div>}</main><Footer /></div>
}
