import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicMatches } from '@/lib/content/public'
import { Calendar, MapPin } from 'lucide-react'

const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value)) : 'Tarih belirtilmedi'
const labels = { scheduled: 'Planlandı', postponed: 'Ertelendi', completed: 'Tamamlandı', cancelled: 'İptal edildi' }

export default async function MatchesPage() {
  const matches = await getPublicMatches()
  return <div className="min-h-screen overflow-x-clip bg-slate-50 text-slate-900"><Header /><section className="border-b border-red-900 bg-gradient-to-br from-red-800 via-red-700 to-slate-900 py-14 text-white sm:py-16"><div className="container mx-auto px-4"><p className="text-sm font-bold uppercase tracking-[.2em] text-red-200">Fikstür merkezi</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Maçlar</h1><p className="mt-4 max-w-2xl text-base leading-7 text-red-100 sm:text-lg">Fikstür, maç detayları ve sonuçlar.</p></div></section><main className="container mx-auto px-4 py-10 sm:py-14">{matches.length ? <div className="grid gap-5 lg:grid-cols-2">{matches.map((match) => <article key={match.id} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="truncate text-sm font-bold text-red-700">{match.teams?.name || 'Takım'}</p><p className="mt-1 text-sm text-slate-500">{match.competition}{match.week ? ` · ${match.week}. hafta` : ''}</p></div><span className="w-fit shrink-0 rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{labels[String(match.status) as keyof typeof labels] ?? 'Durum bilinmiyor'}</span></div><div className="my-7 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><strong className="min-w-0 truncate text-left text-base sm:text-lg">{match.home_team}</strong><span className="rounded-full bg-red-50 px-3 py-2 text-sm font-black text-red-800">{match.status === 'completed' ? `${match.home_score} - ${match.away_score}` : 'VS'}</span><strong className="min-w-0 truncate text-right text-base sm:text-lg">{match.away_team}</strong></div><div className="grid gap-2 border-t border-slate-100 pt-4 text-sm text-slate-600 sm:grid-cols-2"><span className="flex min-w-0 items-start"><Calendar className="mr-2 mt-0.5 h-4 w-4 shrink-0 text-red-600" />{formatDate(match.match_date)}{match.kickoff_time ? ` · ${match.kickoff_time.slice(0, 5)}` : ''}</span>{match.stadium ? <span className="flex min-w-0 items-start"><MapPin className="mr-2 mt-0.5 h-4 w-4 shrink-0 text-red-600" /><span className="break-words">{match.stadium}</span></span> : null}</div></article>)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Calendar className="mx-auto h-12 w-12 text-slate-300" /><h2 className="mt-4 text-xl font-bold text-slate-700">Henüz maç kaydı yok</h2><p className="mt-2 text-slate-500">Yeni fikstür ve sonuçlar burada görünecek.</p></div>}</main><Footer /></div>
}
