import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicGallery } from '@/lib/content/public'
import Image from 'next/image'
import { Camera, Calendar } from 'lucide-react'

const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(value)) : 'Tarih belirtilmedi'

export default async function GalleryPage() {
  const items = await getPublicGallery()
  return <div className="min-h-screen overflow-x-clip bg-slate-50 text-slate-900"><Header /><section className="border-b border-red-900 bg-gradient-to-br from-red-800 via-red-700 to-slate-900 py-14 text-white sm:py-16"><div className="container mx-auto px-4"><p className="text-sm font-bold uppercase tracking-[.2em] text-red-200">Anılar</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Galeri</h1><p className="mt-4 max-w-2xl text-base leading-7 text-red-100 sm:text-lg">Kulübümüzden sahaya ve hayata dair kareler.</p></div></section><main className="container mx-auto px-4 py-10 sm:py-14">{items.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="group min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="relative aspect-[4/3] bg-slate-100"><Image src={item.signedUrl} alt={item.title} fill unoptimized className="object-cover transition duration-500 group-hover:scale-[1.03]" sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" /></div><div className="p-5"><div className="flex flex-wrap justify-between gap-x-3 gap-y-1 text-xs text-slate-500"><span className="font-bold uppercase tracking-wide text-red-700">{item.category}</span><span className="flex items-center"><Calendar className="mr-1 h-4 w-4" />{formatDate(item.taken_at)}</span></div><h2 className="mt-3 font-bold text-slate-900">{item.title}</h2>{item.description ? <p className="mt-1 text-sm leading-6 text-slate-600">{item.description}</p> : null}</div></article>)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Camera className="mx-auto h-12 w-12 text-slate-300" /><h2 className="mt-4 text-xl font-bold text-slate-700">Henüz galeri içeriği yok</h2><p className="mt-2 text-slate-500">Yayınlanan görseller burada gösterilecek.</p></div>}</main><Footer /></div>
}
