import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicSettings } from '@/lib/content/public'
import { Facebook, Instagram, Mail, MapPin, Phone, Youtube } from 'lucide-react'

export default async function ContactPage() {
  const settings = await getPublicSettings()
  const items = [{ label: 'Adres', value: settings?.address, Icon: MapPin }, { label: 'Telefon', value: settings?.phone, Icon: Phone }, { label: 'E-posta', value: settings?.email, Icon: Mail }].filter((item) => item.value)
  const social = [{ label: 'Instagram', href: settings?.instagram_url, Icon: Instagram }, { label: 'Facebook', href: settings?.facebook_url, Icon: Facebook }, { label: 'YouTube', href: settings?.youtube_url, Icon: Youtube }].filter((item) => item.href)
  return <div className="min-h-screen overflow-x-clip bg-slate-50 text-slate-900"><Header /><section className="border-b border-red-900 bg-gradient-to-br from-red-800 via-red-700 to-slate-900 py-14 text-white sm:py-16"><div className="container mx-auto px-4"><p className="text-sm font-bold uppercase tracking-[.2em] text-red-200">Bize ulaşın</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">İletişim</h1><p className="mt-4 max-w-2xl text-base leading-7 text-red-100 sm:text-lg">Kulübümüzle iletişime geçin ve bizi takip edin.</p></div></section><main className="container mx-auto px-4 py-10 sm:py-14"><div className="mx-auto max-w-5xl rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><p className="text-sm font-bold uppercase tracking-wide text-red-700">Kulüp bilgileri</p><h2 className="mt-1 text-2xl font-black tracking-tight text-slate-900">İletişim kanalları</h2>{items.length ? <div className="mt-7 grid gap-4 md:grid-cols-3">{items.map(({ label, value, Icon }) => <div key={label} className="min-w-0 rounded-xl border border-slate-200 p-5"><Icon className="h-6 w-6 text-red-600" /><h3 className="mt-4 font-bold text-slate-900">{label}</h3>{label === 'Telefon' ? <a className="mt-2 block break-words text-sm leading-6 text-slate-600 hover:text-red-700" href={`tel:${value}`}>{value}</a> : label === 'E-posta' ? <a className="mt-2 block break-all text-sm leading-6 text-slate-600 hover:text-red-700" href={`mailto:${value}`}>{value}</a> : <p className="mt-2 whitespace-pre-line break-words text-sm leading-6 text-slate-600">{value}</p>}</div>)}</div> : <p className="mt-5 text-slate-500">İletişim bilgileri yakında paylaşılacak.</p>}{social.length ? <div className="mt-8 border-t border-slate-100 pt-6"><h3 className="font-bold text-slate-900">Bizi takip edin</h3><div className="mt-4 flex flex-wrap gap-3">{social.map(({ label, href, Icon }) => <a key={label} href={href} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white transition hover:bg-red-800"><Icon className="h-4 w-4" />{label}</a>)}</div></div> : null}</div></main><Footer /></div>
}
