import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { getPublicSettings } from '@/lib/content/public'
import { Facebook, Instagram, Mail, MapPin, Phone, Youtube } from 'lucide-react'

export default async function ContactPage() {
  const settings = await getPublicSettings()
  const items = [{ label: 'Adres', value: settings?.address, Icon: MapPin }, { label: 'Telefon', value: settings?.phone, Icon: Phone }, { label: 'E-posta', value: settings?.email, Icon: Mail }].filter((item) => item.value)
  const social = [{ label: 'Instagram', href: settings?.instagram_url, Icon: Instagram }, { label: 'Facebook', href: settings?.facebook_url, Icon: Facebook }, { label: 'YouTube', href: settings?.youtube_url, Icon: Youtube }].filter((item) => item.href)
  return <div className="min-h-screen bg-gray-50"><Header /><section className="bg-gradient-to-r from-red-600 via-red-700 to-red-800 py-16 text-white"><div className="container mx-auto px-4 text-center"><h1 className="text-4xl font-bold md:text-5xl">İletişim</h1><p className="mt-4 text-xl text-red-100">Bizimle iletişime geçin</p></div></section><main className="container mx-auto px-4 py-12"><div className="mx-auto max-w-4xl rounded-xl bg-white p-6 shadow md:p-10"><h2 className="text-2xl font-bold text-gray-900">Kulüp iletişim bilgileri</h2>{items.length ? <div className="mt-6 grid gap-5 md:grid-cols-3">{items.map(({ label, value, Icon }) => <div key={label} className="rounded-lg border p-4"><Icon className="h-7 w-7 text-red-600" /><h3 className="mt-3 font-semibold">{label}</h3>{label === 'Telefon' ? <a className="mt-1 block text-gray-600 hover:text-red-700" href={`tel:${value}`}>{value}</a> : label === 'E-posta' ? <a className="mt-1 block text-gray-600 hover:text-red-700" href={`mailto:${value}`}>{value}</a> : <p className="mt-1 whitespace-pre-line text-gray-600">{value}</p>}</div>)}</div> : <p className="mt-4 text-gray-500">İletişim bilgileri yakında paylaşılacak.</p>}{social.length ? <div className="mt-8 border-t pt-6"><h3 className="font-semibold">Bizi takip edin</h3><div className="mt-3 flex gap-3">{social.map(({ label, href, Icon }) => <a key={label} href={href} className="flex items-center gap-2 rounded bg-red-700 px-3 py-2 text-sm font-semibold text-white hover:bg-red-800"><Icon className="h-4 w-4" />{label}</a>)}</div></div> : null}</div></main><Footer /></div>
}
